In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[1.3452e-43, 0.0000e+00, 0.0000e+00],
        [9.2196e-41, 0.0000e+00, 0.0000e+00],
        [3.0602e+15, 4.5713e-41, 3.2686e+18],
        [4.5713e-41, 1.4013e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 8.2314e+18]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1023, 0.8398, 0.6919],
        [0.0462, 0.6403, 0.8834],
        [0.5138, 0.2689, 0.3500],
        [0.1976, 0.6418, 0.3112],
        [0.2311, 0.8021, 0.1595]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.6945,  0.5563, -0.3806],
        [ 0.0947,  1.3605, -0.4686],
        [-0.2065, -0.2989,  0.5086],
        [-0.1787, -0.1229,  1.0110],
        [-0.4676,  1.0866,  0.4741]])


In [7]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.7105,  1.3652,  0.4597],
        [ 0.1912,  2.2684, -0.0818],
        [-0.1933,  0.0170,  1.0996],
        [ 0.2925,  0.7924,  1.6051],
        [-0.0554,  1.7360,  0.7139]])


In [8]:
print(torch.add(x, y))

tensor([[ 0.7105,  1.3652,  0.4597],
        [ 0.1912,  2.2684, -0.0818],
        [-0.1933,  0.0170,  1.0996],
        [ 0.2925,  0.7924,  1.6051],
        [-0.0554,  1.7360,  0.7139]])


In [9]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.7105,  1.3652,  0.4597],
        [ 0.1912,  2.2684, -0.0818],
        [-0.1933,  0.0170,  1.0996],
        [ 0.2925,  0.7924,  1.6051],
        [-0.0554,  1.7360,  0.7139]])


In [10]:
y.add_(x)
print(y)

tensor([[ 0.7105,  1.3652,  0.4597],
        [ 0.1912,  2.2684, -0.0818],
        [-0.1933,  0.0170,  1.0996],
        [ 0.2925,  0.7924,  1.6051],
        [-0.0554,  1.7360,  0.7139]])


In [11]:
print(x[:,1])

tensor([ 0.5563,  1.3605, -0.2989, -0.1229,  1.0866])


In [12]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 2)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([8, 2])


In [13]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.1986])
-0.19860762357711792


In [14]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [15]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [16]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [17]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [18]:
x = torch.ones(3, requires_grad=True)
y = 2 * x
z = y  ** 2
print(z, '\n', x)

tensor([4., 4., 4.], grad_fn=<PowBackward0>) 
 tensor([1., 1., 1.], requires_grad=True)


In [19]:
v = torch.tensor([0.1, 1., 0.001])
z.backward(v)
print(y.grad, '\n', x.grad)

None 
 tensor([0.8000, 8.0000, 0.0080])


In [20]:
print(y.requires_grad)

True


In [21]:
x = torch.ones(3,3,3)
print(x)
print(x.view(-1, 9))

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])


In [23]:
torch.cuda

<module 'torch.cuda' from '/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py'>