In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[1.4013e-45, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0722, 0.4211, 0.0682],
        [0.8990, 0.4002, 0.6063],
        [0.1047, 0.6216, 0.0074],
        [0.5294, 0.1970, 0.2993],
        [0.9124, 0.5771, 0.0732]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [9]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.5303,  1.0578,  0.6781],
        [ 1.5505, -0.1357, -0.6578],
        [ 0.0488, -0.1197,  0.0386],
        [-0.7187, -1.5097,  1.3905],
        [ 0.7955,  1.5056,  1.1488]])


In [10]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.8520,  1.5964,  0.8638],
        [ 2.5334,  0.4917, -0.4869],
        [ 0.1425,  0.6625,  0.8583],
        [-0.1626, -1.1732,  2.1077],
        [ 1.0072,  2.0802,  1.7925]])


In [11]:
print(torch.add(x, y))

tensor([[ 0.8520,  1.5964,  0.8638],
        [ 2.5334,  0.4917, -0.4869],
        [ 0.1425,  0.6625,  0.8583],
        [-0.1626, -1.1732,  2.1077],
        [ 1.0072,  2.0802,  1.7925]])


In [12]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.8520,  1.5964,  0.8638],
        [ 2.5334,  0.4917, -0.4869],
        [ 0.1425,  0.6625,  0.8583],
        [-0.1626, -1.1732,  2.1077],
        [ 1.0072,  2.0802,  1.7925]])


In [13]:
y.add_(x)
print(y)

tensor([[ 0.8520,  1.5964,  0.8638],
        [ 2.5334,  0.4917, -0.4869],
        [ 0.1425,  0.6625,  0.8583],
        [-0.1626, -1.1732,  2.1077],
        [ 1.0072,  2.0802,  1.7925]])


In [17]:
print(x[:,1])

tensor([ 1.0578, -0.1357, -0.1197, -1.5097,  1.5056])


In [21]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 2)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([8, 2])


In [22]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.1605])
-0.16051717102527618


In [23]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [24]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [25]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [26]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [38]:
x = torch.ones(3, requires_grad=True)
y = 2 * x
z = y  ** 2
print(z, '\n', x)

tensor([4., 4., 4.], grad_fn=<PowBackward0>) 
 tensor([1., 1., 1.], requires_grad=True)


In [39]:
v = torch.tensor([0.1, 1., 0.001])
z.backward(v)
print(y.grad, '\n', x.grad)

None 
 tensor([0.8000, 8.0000, 0.0080])


In [35]:
print(y.requires_grad)

True


In [41]:
x = torch.ones(3,3,3)
print(x)
print(x.view(-1, 9))

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])
